<?php
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet/leaflet.css', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet/leaflet.js', 'Mapping'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet.markercluster/MarkerCluster.css', 'Mapping'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet.markercluster/MarkerCluster.Default.css', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet.markercluster/leaflet.markercluster.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet.providers/leaflet-providers.js', 'Mapping'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet.groupedlayercontrol/leaflet.groupedlayercontrol.min.css', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet.groupedlayercontrol/leaflet.groupedlayercontrol.min.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/control.opacity.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/mapping-block.js', 'Mapping'));
if ($isTimeline) {
    $this->headLink()->appendStylesheet('https://cdn.knightlab.com/libs/timeline3/latest/css/timeline.css');
    $this->headScript()->appendFile('https://cdn.knightlab.com/libs/timeline3/latest/js/timeline.js');
    $this->headLink()->appendStylesheet($this->assetUrl('css/timeline.css', 'Mapping'));  
}
// Set the classes for the mapping block container div.
$mappingBlockClasses = ['mapping-block'];
if ($isTimeline) {
    $mappingBlockClasses[] = 'timeline';
    $timenavPosition = $data['timeline']['timenav_position'];
    $mappingBlockClasses[] = $timenavPosition;
    if ('full_width_below' === $timenavPosition) {
        $mappingBlockClasses[] = 'timenav-full-width-below';
    }
    if ('full_width_above' === $timenavPosition) {
        $mappingBlockClasses[] = 'timenav-full-width-above';        
    }
}
?>
<div class="<?php echo implode(' ', $mappingBlockClasses); ?>">
    <?php if ($isTimeline): ?>
    <div class='mapping-timeline' style="height: 400px" data-data="<?php echo $this->escapeHtml(json_encode($timelineData)); ?>" data-options="<?php echo $this->escapeHtml(json_encode($timelineOptions)); ?>"></div>
    <div class="mapping-map" style="height:400px;" data-markers="<?php echo $this->escapeHtml(json_encode($markers)); ?>" data-data="<?php echo $this->escapeHtml(json_encode($data)); ?>"></div>
    <?php else: ?>
    <div class="mapping-map" style="height:500px;" data-markers="<?php echo $this->escapeHtml(json_encode($markers)); ?>" data-data="<?php echo $this->escapeHtml(json_encode($data)); ?>"></div>
    <?php endif; ?>

    <?php foreach ($markers as $marker): ?>
    <div class="mapping-marker-popup-content" style="display:none;" data-marker-id="<?php echo $this->escapeHtml($marker->id()); ?>" data-item-id="<?php echo $this->escapeHtml($marker->item()->id()); ?>">
        <?php echo $this->partial('/common/block-layout/mapping-block-popup-content', ['marker' => $marker]); ?>
    </div>
    <?php endforeach; ?>
</div>
