<?php

// clean this up and convert to a controller

$response = file_get_contents($section['manifest']);
$json = json_decode($response);

if (in_array('https://iiif.io/api/presentation/3/context.json', $json->{'@context'})) :

    $label = $json->label->en[0];
    $summary = $json->summary->en[0];
    $image = $json->items[0]->items[0]->items[0]->body[0]->service->{'@id'}
    ;
    $canvas = $image . '/' . $section['region'] . '/!1000,1000/0/default.jpg';

?>

    <figure class="exposition-teaser"
            data-manifest="<?php print $section['manifest']; ?>">
        <a href="#modal">
            <img src="<?php print $canvas; ?>"
                 alt="<?php print $label; ?>"
            />
        </a>
        <div class="exposition-teaser--content">
            <figcaption>
                <cite><?php print $label; ?></cite>
                <p><?php print $summary; ?></p>
            </figcaption>
            <ul>
                <li><a href="#modal">Expand Item</a></li>
                <li><a href="#dcuri">View Digital Collection</a></li>
            </ul>
        </div>
    </figure>

<?php endif; ?>
