<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteBlockAttachmentRepresentation[] $attachments
 */

?>
<section class="exposition exposition-section">
    <h2>
        <?php print $section['heading']; ?>
    </h2>
    <div class="exposition-content">
        <div class="exposition-content--body">
            <?php print $section['body']; ?>
        </div>
        <div class="exposition-content--item">
            <?php echo $this->partial('exposition/teaser.phtml'); ?>
        </div>
    </div>
</section>
