<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$siteSummary = $site->summary();
$siteId = $site->id();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->jsTranslate();
$this->trigger('view.layout');
$userBar = $this->userBar();

if ($this->themeSetting('utk_background')):
    $source = $this->themeSettingAssetUrl('utk_background');
    $backgroundStyle = 'style="background-image: url(' . $source . ');"';
else :
    $backgroundStyle = null;
endif;

?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>
    <?php echo $this->headScript(); ?>
    <?php if ($subtheme = $this->themeSetting('utk_subtheme')): ?>
        <?php // append  subtheme ?>
    <?php endif; ?>
    <script crossorigin src="https://unpkg.com/react@16/umd/react.production.min.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js"></script>
    <script async src="https://www.lib.utk.edu/assets/universal-header.js?v=1.0.3"></script>
</head>
<?php echo $this->htmlElement('body'); ?>
    <div id="utk-lib-header" data-page-title="Digital Exhibits - <?php echo $escape($siteTitle); ?> | Libraries at University of Tennessee, Knoxville"></div>
    <div class="exhibit"  <?php echo $backgroundStyle; ?>>
        <header class="exhibit-masthead">
            <div class="exhibit-navbar container">
                <nav>
                    <?php
                    echo $site->publicNav()->menu()->renderMenu(null, [
                        'maxDepth' => $this->themeSetting('nav_depth') - 1
                    ]);
                    ?>
                </nav>
                <div class="exhibit-toggle">
                    <?php

                        // clean this up and convert to a controller
                        $response = file_get_contents("https://tennessee.omeka.net/api/sites");
                        $sites = json_decode($response);
                        $instance = array();

                        foreach ($sites as $key => $site) :
                            if ($site->{"o:is_public"} === true) :
                                $instance[$key]['id'] = $site->{"o:id"};
                                $instance[$key]['slug'] = $site->{"o:slug"};
                                $instance[$key]['title'] = $site->{"o:title"};

                                if ($site->{"o:id"} === $siteId) :
                                    $instance[$key]['selected'] = ' selected="selected"';
                                else:
                                    $instance[$key]['selected'] = null;
                                endif;
                            endif;
                        endforeach;

                    ?>
                    <label for="exhibit-toggle" class="sr-only">Select Exhibit</label>
                    <select id="exhibit-toggle" name="exhibit-toggle">
                        <?php
                            foreach ($instance as $site) :
                                echo "<option value='/s/". $site['slug'] ."' id=". $site['id'] . $site['selected'] . ">" . $site['title'] . "</option>";
                            endforeach;
                        ?>
                    </select>
                </div>
            </div>
            <div class="exhibit-title">
                <h2>
                    <?php echo $escape($siteTitle); ?>
                </h2>
                <span class="exhibit-summary">
                    <?php echo $escape($siteSummary); ?>
                </span>
            </div>
        </header>
        <main id="content" role="main" class="container">
            <?php echo $this->content; ?>
        </main>
        <div  class="container">
            <?php if ($footerContent = $this->themeSetting('utk_footer')): ?>
                <?php echo $footerContent; ?>
            <?php endif; ?>
        </div>
    </div>
<footer id="utk-lib-footer"></footer>
</body>
</html>
