<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteBlockAttachmentRepresentation[] $attachments
 */

if ($mode === '') {
    $mode = 'manifest';
}
?>

<div id="simple-mirador-<?php echo $blockId; ?>"
     class="simple-mirador"
     data-mode="<?php echo $mode; ?>"
     data-config="<?php echo htmlspecialchars(json_encode($config)); ?>"
     data-manifest="<?php echo $manifest; ?>">
</div>

<script type="text/javascript"
        src="<?php echo $this->assetUrl('mirador.js', 'SimpleMirador'); ?>">
</script>

<style>
    .simple-mirador {
        height: calc(600px);
        width: calc(100%);
        position: relative;
        margin: 1em auto 3em;
    }
</style>