<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteBlockAttachmentRepresentation[] $attachments
 */

?>

<div id="simple-mirador"
     data-manifest="<?php echo $manifest; ?>">
</div>

<script type="text/javascript"
        src="<?php echo $this->assetUrl('mirador.js', 'SimpleMirador'); ?>">
</script>

<style>
    #mirador {
        height: calc(600px);
        width: calc(100%);
        position: relative;
        margin: 1em auto 3em;
    }
</style>